# PDS09 10th Class #
* File Handling
* Numpy

In [2]:
#file handling

#create a file
f = open("file.txt", "w")
for i in range(10):
    f.write(f"This is line {(i+1)}\n")
f.close()

In [3]:
#read a file
f = open("file.txt", "r")
print(f.read())
f.close()

This is line 1
This is line 2
This is line 3
This is line 4
This is line 5
This is line 6
This is line 7
This is line 8
This is line 9
This is line 10



In [4]:
import os
os.remove("file.txt")

#check if file exists
if os.path.exists("file.txt"):
    os.remove("file.txt")
else:
    print("The file does not exist")

The file does not exist


In [5]:
#Practice problem

#1 Create a file named contents
file = open('contents.txt', 'w')

#2 Append the following line: 'Listen, smile, agree, and then do whatever you were gonna do anyway'
message = 'Listen, smile, agree, and then do whatever you were gonna do anyway'
file.write(message)
file.close()

#3 Read the flie and print it
file = open('contents.txt', 'r')
print(file.read(), '\n')
file.close()

#4 Append another line
file = open('contents.txt', 'a')
message = '\n\t - Quote by Robert Downey Jr'
file.write(message)
file.close()

#5 Overwrite the entire file with custom quote
file = open('contents.txt', 'w')
message = 'Good can come out of even the darkest acts'
file.write(message)
file.close()

#6 Create another file named extra.txt
new_file = open('extra.txt', 'w+')
new_file.write('Gonna remove it soon')
new_file.close()

#7 Read the file
new_file = open('extra.txt', 'r')
print(new_file.read())
new_file.close()

#8 Delete the file
import os
# os.remove('extra.txt')

if os.path.exists('extra.txt'):
    print('The file exists')
else:
    print('The file does not exist')

Listen, smile, agree, and then do whatever you were gonna do anyway 

Gonna remove it soon
The file exists


In [6]:
#Numpy
import numpy as np

#1 Create a numpy array of 5 zeros
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[0])
print(arr)
print(type(arr))

print(arr[0:3] + 5)

print(arr[-3:-1])
print(arr[-3:-2])

1
[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>
[6 7 8]
[5 6]
[5]


In [7]:
#2D array
arr2 = np.array([[1, 2, 3, 4, 5],
                 [6, 7, 8, 9, 10]])

print('2nd element on 1st row: ', arr2[0, 1])
print('2nd row 5th column: ', arr2[1, 4])

2nd element on 1st row:  2
2nd row 5th column:  10


In [8]:
#3D array
arr3 = np.array([[[1, 2, 3],
                  [4, 5, 6]],
                 [[7, 8, 9],
                  [1, 3, 5]]])

print(arr3)
print('Element at position ',arr3[0, 1, 2])

print(arr3.ndim)

print(arr3.flatten())

print(arr3.mean())

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 3 5]]]
Element at position  6
3
[1 2 3 4 5 6 7 8 9 1 3 5]
4.5


In [9]:
#copy array
arr4 = arr3.copy()
arr4[0, 1, :] = 100
print(arr3, '\n')
print(arr4)


[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 3 5]]] 

[[[  1   2   3]
  [100 100 100]]

 [[  7   8   9]
  [  1   3   5]]]


In [10]:
#onws and views

arr5 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
# print(arr5)

arr6 = arr5.copy()

arr7 = arr5.view()

print(arr5.base)
print(arr6.base)
print(arr7.base)

None
None
[1 2 3 4 5 6 7 8 9]


In [12]:
#Reshape

arr8 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18])

arr9 =  arr8.reshape(3, 3, 2)

print(arr8)
print(arr9)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]
