# PDS09 15th Class #
* Numpy by Insturctor

In [1]:
import numpy as np

In [29]:
arr = np.array(
    [
        [1, 2, 3, 4, 5],
        [2, 4, 6, 8, 10]
    ]
    )

arr2 = arr.reshape(5, 2)

arr2.shape
arr

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10]])

In [19]:
print(arr.mean(axis=0))
print(arr.sum(axis=1))

[1.5 3.  4.5 6.  7.5]
[15 30]


In [22]:
print(arr[0][2:5])

[3 4 5]


In [28]:
narr = np.array([10, 6, 4, 8, 20, 5])

narr.sort()
narr[-4:]

array([ 6,  8, 10, 20])

In [34]:
print(arr[1][::2])
arr[1:, 2:6]

[ 2  6 10]


array([[ 6,  8, 10]])

In [42]:
# Conditional Array
c_arr = arr % 2 == 0
c_arr

f_arr = arr[c_arr]
f_arr.reshape(7,1)

array([[ 2],
       [ 4],
       [ 2],
       [ 4],
       [ 6],
       [ 8],
       [10]])

In [44]:
#Count Elements

np.unique(arr, return_counts=True)

(array([ 1,  2,  3,  4,  5,  6,  8, 10]), array([1, 2, 1, 2, 1, 1, 1, 1]))

In [47]:
np.sort(arr)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10]])