In [8]:
import numpy as np

x = [1, 2, 3, 4, 5]
y = [9, 8, 7, 6]

x *= 2

print(x)

x,y = np.array(x), np.array(y)

x *= 2

print(x)
print(y)

print(np.convolve(x, y))

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10  2  4  6  8 10]
[9 8 7 6]
[ 18  52 100 160 220 190 170 160 160 220 172 118  60]


# Start
.code

In [2]:
import numpy as np

z = np.zeros(5)

o = np.ones(10)

print(o)

print(z)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0.]


In [4]:
data = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])


In [5]:
a = [[1,2], [3,4]]
b = [[1,2], [3,4]]

x = np.array(a)
y = np.array(b)

print(x@y)
print(x.dot(y))
print(np.dot(x, y))

[[ 7 10]
 [15 22]]
[[ 7 10]
 [15 22]]
[[ 7 10]
 [15 22]]


In [107]:
np.random.seed(10)

data = np.array([np.random.randint(40, 101, (4,5))])

print(data)
print("Max :", data.max())
print("std: ", data.std())

new_data = data - 10

re = new_data.reshape(2,10)
re

[[[49 76 55 40 89]
  [99 68 65 69 88]
  [69 89 98 48 49]
  [40 82 80 94 76]]]
Max : 99
std:  18.65281480098915


array([[39, 66, 45, 30, 79, 89, 58, 55, 59, 78],
       [59, 79, 88, 38, 39, 30, 72, 70, 84, 66]])

# pandas

In [148]:
import pandas as pd

data = {"Name":["Avro", "Saeed", "Refat", "Nuru", "Shouvik"], "Age":[23, 30, 22, 35, 40], "CGP":[3.5, 3.9, 3.25,4, 3.99]}

dt = pd.Series(data)

df = pd.DataFrame(data)
# df.fillna("Name", 'Nuru')
print(df["Age"])

f_dt = df[(df['Age'] > 20)]
print(f_dt)

f_dt = f_dt.sort_values("CGP", ascending=False)
print(f_dt)

print(df.describe())

f_dt.to_csv("my_first_csv")

0    23
1    30
2    22
3    35
4    40
Name: Age, dtype: int64
      Name  Age   CGP
0     Avro   23  3.50
1    Saeed   30  3.90
2    Refat   22  3.25
3     Nuru   35  4.00
4  Shouvik   40  3.99
      Name  Age   CGP
3     Nuru   35  4.00
4  Shouvik   40  3.99
1    Saeed   30  3.90
0     Avro   23  3.50
2    Refat   22  3.25
             Age       CGP
count   5.000000  5.000000
mean   30.000000  3.728000
std     7.713624  0.336407
min    22.000000  3.250000
25%    23.000000  3.500000
50%    30.000000  3.900000
75%    35.000000  3.990000
max    40.000000  4.000000
